### ISSUE TITLE
August 2017 Incident and Solution

### ISSUE THREAD

**Issue by dignifiedquire** [protocol/gaps#3]
Very likely due to veeeery outdated gems in the application:

```
017-08-25T13:32:33.089564+00:00 app[web.1]: [4] Refreshing expired token: user="<User[model_bV0x1UhSB4] google_id=\"****\" email=\"dignifiedquire@protocol.ai\">"
2017-08-25T13:32:33.111743+00:00 app[web.1]: [4] Refreshing expired token: user="<User[model_bV0x1UhSB4] google_id=\"****\" email=\"dignifiedquire@protocol.ai\">"
2017-08-25T13:32:33.327840+00:00 app[web.1]: bundler: failed to load command: bin/gaps_server.rb (bin/gaps_server.rb)
2017-08-25T13:32:33.327418+00:00 app[web.1]: == Sinatra has ended his set (crowd applauds)
2017-08-25T13:32:33.328040+00:00 app[web.1]: Mongo::OperationFailure: Database command 'update' failed: Unknown option to update command: w (raised from thread pool)
2017-08-25T13:32:33.328044+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/db.rb:610:in `rescue in command'
2017-08-25T13:32:33.328045+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/db.rb:606:in `command'
2017-08-25T13:32:33.328047+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:55:in `block in instrument'
2017-08-25T13:32:33.328046+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:314:in `block in send_write_command'
2017-08-25T13:32:33.328048+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:20:in `instrument'
2017-08-25T13:32:33.328048+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:54:in `instrument'
2017-08-25T13:32:33.328049+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:313:in `send_write_command'
2017-08-25T13:32:33.328050+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1104:in `send_write'
2017-08-25T13:32:33.328051+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/collection.rb:497:in `update'
2017-08-25T13:32:33.328051+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.12.5/lib/mongo/collection.rb:361:in `save'
2017-08-25T13:32:33.328052+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:136:in `save_to_collection'
2017-08-25T13:32:33.328052+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations.rb:88:in `save_to_collection'
2017-08-25T13:32:33.328053+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/safe.rb:27:in `save_to_collection'
2017-08-25T13:32:33.328054+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:130:in `update'
2017-08-25T13:32:33.328055+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:25:in `block in update'
2017-08-25T13:32:33.328056+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
2017-08-25T13:32:33.328057+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-08-25T13:32:33.328055+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2017-08-25T13:32:33.328057+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/embedded_callbacks.rb:77:in `run_callbacks'
2017-08-25T13:32:33.328058+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:25:in `update'
2017-08-25T13:32:33.328059+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:121:in `create_or_update'
2017-08-25T13:32:33.328060+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:17:in `block in create_or_update'
2017-08-25T13:32:33.328060+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
2017-08-25T13:32:33.328061+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
2017-08-25T13:32:33.328062+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2017-08-25T13:32:33.328062+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
2017-08-25T13:32:33.328063+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
2017-08-25T13:32:33.328063+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2017-08-25T13:32:33.328065+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-08-25T13:32:33.328064+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
2017-08-25T13:32:33.328066+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/embedded_callbacks.rb:77:in `run_callbacks'
2017-08-25T13:32:33.328066+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb:17:in `create_or_update'
2017-08-25T13:32:33.328067+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:103:in `save'
2017-08-25T13:32:33.328068+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb:17:in `block in save'
2017-08-25T13:32:33.328068+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb:27:in `clear_changes'
2017-08-25T13:32:33.328097+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb:17:in `save'
2017-08-25T13:32:33.328099+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/validations.rb:22:in `save'
2017-08-25T13:32:33.328099+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/identity_map.rb:87:in `save'
2017-08-25T13:32:33.328100+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb:108:in `save!'
2017-08-25T13:32:33.328101+00:00 app[web.1]:   /app/lib/gaps/db/user.rb:246:in `do_refresh'
2017-08-25T13:32:33.328101+00:00 app[web.1]:   /app/lib/gaps/db/user.rb:103:in `client'
2017-08-25T13:32:33.328103+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:149:in `lister_client'
2017-08-25T13:32:33.328103+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:159:in `get_client'
2017-08-25T13:32:33.328104+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:173:in `request'
2017-08-25T13:32:33.328104+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:223:in `block in request_all'
2017-08-25T13:32:33.328105+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/range/each.rb:7:in `each'
2017-08-25T13:32:33.328106+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
2017-08-25T13:32:33.328107+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:219:in `request_all'
2017-08-25T13:32:33.328107+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:68:in `membership_list'
2017-08-25T13:32:33.328108+00:00 app[web.1]:   /app/lib/gaps/requestor.rb:58:in `block in membership_list_for_group'
2017-08-25T13:32:33.328108+00:00 app[web.1]:   /app/lib/gaps/db/cache.rb:68:in `call'
2017-08-25T13:32:33.328109+00:00 app[web.1]:   /app/lib/gaps/db/cache.rb:68:in `block in cache_lookup'
2017-08-25T13:32:33.328110+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
2017-08-25T13:32:33.328111+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
2017-08-25T13:32:33.328111+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
2017-08-25T13:32:33.328112+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
2017-08-25T13:32:33.328113+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
2017-08-25T13:32:33.328113+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'
2017-08-25T13:32:33.328134+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
2017-08-25T13:32:33.505472+00:00 heroku[web.1]: Process exited with status 1
2017-08-25T13:32:33.519147+00:00 heroku[web.1]: State changed from up to crashed
2017-08-25T13:32:38.682755+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=protocol-com.herokuapp.com request_id=58b563d2-e4ea-45b4-a257-551fe72b6275 fwd="173.245.203.70" dyno=web.1 connect=5000ms service= status=503 bytes= protocol=https
2017-08-25T13:32:39.612824+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=protocol-com.herokuapp.com request_id=d35cbadc-a681-4735-b582-94505b1641dd fwd="173.245.203.70" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by dignifiedquire** [comment]
Seems the same issue as https://github.com/stripe/gaps/issues/37

**Comment by dignifiedquire** [comment]
Fixed by downgrading the mongodb version on heroku to 3.0
